name: Docker Deployment
author: Al-waleed Shihadeh <wshihadeh.dev@gmail.com>
description: A GitHub Action that supports docker-compose and Docker Swarm deployments
inputs:
  ssh_private_key:
    description: SSH private key used to connect to the docker host
    required: true
outputs:
  runlog: 
    description: 'The stout and sterr from remote server'

runs:
  using: docker
  image: Dockerfile

branding:
  icon: send
  color: green

